# Generated by Django 4.0.2 on 2022-02-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_type', models.IntegerField()),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
