# Generated by Django 4.0.2 on 2022-02-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_communityjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('post_type', models.IntegerField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
            ],
        ),
    ]
