# Generated by Django 4.0.2 on 2022-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='indices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
