# Generated by Django 4.0.2 on 2022-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='instructor_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='is_being_edited',
            field=models.BooleanField(default=False),
        ),
    ]
