# Generated by Django 4.0.2 on 2022-02-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_response_instructor_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='PostResponse',
        ),
    ]
