# Generated by Django 4.0.2 on 2022-03-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_post_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='postresponse',
            name='is_being_edited',
        ),
    ]
